# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_recommendation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avideo_recommendation.proto\x12\nml_feed_py\"D\n\nMLPostItem\x12\x0f\n\x07post_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61nister_id\x18\x02 \x01(\t\x12\x10\n\x08video_id\x18\x03 \x01(\t\":\n\x12MLPostItemResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61nister_id\x18\x02 \x01(\t\"v\n\x10WatchHistoryItem\x12\x0f\n\x07post_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61nister_id\x18\x02 \x01(\t\x12\x10\n\x08video_id\x18\x03 \x01(\t\x12\x17\n\x0fpercent_watched\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x8b\x01\n\x12SuccessHistoryItem\x12\x0f\n\x07post_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61nister_id\x18\x02 \x01(\t\x12\x10\n\x08video_id\x18\x03 \x01(\t\x12\x11\n\titem_type\x18\x04 \x01(\t\x12\x17\n\x0fpercent_watched\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"\xd5\x01\n\rMLFeedRequest\x12\x13\n\x0b\x63\x61nister_id\x18\x01 \x01(\t\x12\x33\n\rwatch_history\x18\x02 \x03(\x0b\x32\x1c.ml_feed_py.WatchHistoryItem\x12\x37\n\x0fsuccess_history\x18\x03 \x03(\x0b\x32\x1e.ml_feed_py.SuccessHistoryItem\x12,\n\x0c\x66ilter_posts\x18\x04 \x03(\x0b\x32\x16.ml_feed_py.MLPostItem\x12\x13\n\x0bnum_results\x18\x05 \x01(\r\">\n\x0eMLFeedResponse\x12,\n\x04\x66\x65\x65\x64\x18\x01 \x03(\x0b\x32\x1e.ml_feed_py.MLPostItemResponse2P\n\x06MLFeed\x12\x46\n\x0bget_ml_feed\x12\x19.ml_feed_py.MLFeedRequest\x1a\x1a.ml_feed_py.MLFeedResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MLPOSTITEM']._serialized_start=42
  _globals['_MLPOSTITEM']._serialized_end=110
  _globals['_MLPOSTITEMRESPONSE']._serialized_start=112
  _globals['_MLPOSTITEMRESPONSE']._serialized_end=170
  _globals['_WATCHHISTORYITEM']._serialized_start=172
  _globals['_WATCHHISTORYITEM']._serialized_end=290
  _globals['_SUCCESSHISTORYITEM']._serialized_start=293
  _globals['_SUCCESSHISTORYITEM']._serialized_end=432
  _globals['_MLFEEDREQUEST']._serialized_start=435
  _globals['_MLFEEDREQUEST']._serialized_end=648
  _globals['_MLFEEDRESPONSE']._serialized_start=650
  _globals['_MLFEEDRESPONSE']._serialized_end=712
  _globals['_MLFEED']._serialized_start=714
  _globals['_MLFEED']._serialized_end=794
# @@protoc_insertion_point(module_scope)
